# Generated by Django 3.0.9 on 2020-09-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcore', '0017_author_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['process'],
            },
        ),
    ]
