# Generated by Django 3.0.9 on 2020-09-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcore', '0018_process'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['process'], 'verbose_name_plural': 'Processes'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['priority'], 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='code',
            name='process',
            field=models.ManyToManyField(blank=True, to='lcore.Process'),
        ),
    ]
