# Generated by Django 3.0.9 on 2020-10-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcore', '0020_process_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appfeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_test', models.DateTimeField()),
                ('last_bug', models.CharField(max_length=200)),
                ('bug', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['bug', 'description'],
            },
        ),
    ]
