# Generated by Django 3.0.9 on 2021-07-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcore', '0023_auto_20201102_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('ref_value', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_int', models.IntegerField(blank=True)),
                ('ref_date', models.DateTimeField(blank=True)),
                ('ref_bool', models.BooleanField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='code',
            name='article_file',
            field=models.FileField(blank=True, null=True, upload_to='code_files'),
        ),
    ]
